spring:
  application:
    name: pricing-service

  datasource:
    url: jdbc:h2:mem:pricingservice;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: ps
    password: pricing1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false

  sql:
    init:
      mode: embedded
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: false

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  cache:
    type: caffeine

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  paths-to-match: /api/**

logging:
  level:
    org.springframework: INFO
    com.cirino.rafaela.inditex.pricingservice: DEBUG
    org.springdoc: INFO
  file:
    name: logs/pricing-service.log