name: CI
on:
  push:
    branches:
      - develop
      - main
jobs:
  ci:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5.0.0
        with:
          distribution: zulu
          java-version: 21

      - name: Cache Maven packages
        uses: actions/cache@v4.3.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Unit & Integration Tests
        run: mvn -B verify # -B: --batch-mode

      - name: Generate & Coverage Report
        run: mvn jacoco:report

      - name: Sonar
        if: success() # always() failure() success()
        run: |
          mvn -B verify -DskipTests sonar:sonar \
            -Dsonar.projectKey=rafaelacirino-pricing-service \
            -Dsonar.organization=rafaelacirino \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
